.PHONY: clean All

All:
	@echo "----------Building project:[ bp - Release ]----------"
	@cd "bp" && $(MAKE) -f  "bp.mk"
clean:
	@echo "----------Cleaning project:[ bp - Release ]----------"
	@cd "bp" && $(MAKE) -f  "bp.mk" clean
